### ISSUE TITLE
can not start Arcolinux Tweak Tools

### ISSUE THREAD

**Issue by TheSkyHeart** [arcolinux/arcolinux-tweak-tool#2]
Hi,

I'm facing an issue trying to start the Tweak Tool, when I start it I get the splashscreen then nothing, running it from the command line I get this:

`Traceback (most recent call last):
  File "/usr/share/arcolinux-tweak-tool/arcolinux-tweak-tool.py", line 1350, in <module>
    w = Main()
  File "/usr/share/arcolinux-tweak-tool/arcolinux-tweak-tool.py", line 123, in __init__
    GUI.GUI(self, Gtk, Gdk, GdkPixbuf, base_dir, os)
  File "/usr/share/arcolinux-tweak-tool/GUI.py", line 186, in GUI
    zsh_theme_GUI.GUI(self, Gtk, vboxStack15, zsh_theme, base_dir, GdkPixbuf)
  File "/usr/share/arcolinux-tweak-tool/zsh_theme_GUI.py", line 21, in GUI
    zsh_themes.get_themes(self.zsh_themes)
  File "/usr/share/arcolinux-tweak-tool/zsh_theme.py", line 18, in get_themes
    pos = Functions._get_position(theme_list, "ZSH_THEME=")
  File "/usr/share/arcolinux-tweak-tool/Functions.py", line 211, in _get_position
    position = lists.index(data[0])
IndexError: list index out of range
`

Best Regards

**Comment by arcolinuxz** [comment]
install 
`sudo pacman -S arcolinux-zsh-git oh-my-zsh-git`

and then try again.

**Comment by TheSkyHeart** [comment]
Hi @arcolinuxz,

Thanks a lot for your fast reply, 

but this didn't fix the issue, I do have those packages installed already:

`warning: arcolinux-zsh-git-20.2-9 is up to date -- reinstalling
warning: oh-my-zsh-git-r5620.31eca46ee-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

warning: insufficient columns available for table display
Packages (2) arcolinux-zsh-git-20.2-9  oh-my-zsh-git-r5620.31eca46ee-1

Total Download Size:   0.67 MiB
Total Installed Size:  2.29 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 arcolinux-zsh-gi...    19.2 KiB  0.00   B/s 00:00 [----------------------]   2%
 oh-my-zsh-git-r5...   687.5 KiB  4.48 MiB/s 00:00 [----------------------] 100%
(2/2) checking keys in keyring                     [----------------------] 100%
(2/2) checking package integrity                   [----------------------] 100%
(2/2) loading package files                        [----------------------] 100%
(2/2) checking for file conflicts                  [----------------------] 100%
:: Processing package changes...
(1/2) reinstalling arcolinux-zsh-git               [----------------------] 100%

** The files have been installed in /etc/skel **

(2/2) reinstalling oh-my-zsh-git                   [----------------------] 100%
:: Running post-transaction hooks...
`
please do note that I'm no using oh-my-zsh instead I'm using Pretzo for zsh

Best Regards

**Comment by arcolinuxz** [comment]
you do have to type skel in the terminal
we need our .zshrc

**Comment by TheSkyHeart** [comment]
Thanks a lot @arcolinuxz this worked, but I have in the next versions you can add support for custom zshrc files.

Best Regards

**Comment by arcolinuxz** [comment]
we keep to our own zshrc
