### ISSUE TITLE
Overwrite I3 and polybar config when installing a different WM/DE

### ISSUE THREAD

**Issue by biofilos** [arcolinux/arcolinux-tweak-tool#3]
This is very frustrating.
I would expect the tweak tool to overwrite my I3 config if I re-install I3. However, I do not think it should be a "feature" that when I install Gnome, the tweak tool would overwrite my I3 and polybar configs.
After all this time configuring and customizing I3, I am back to square one, and honestly, out of Arco

**Comment by arcolinuxz** [comment]
Thank you for your report.
We made our ArcoLinux Tweak Tool better.
